run:
  concurrency: 8
  timeout: 5m
linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - paralleltest
    - revive
    - staticcheck
    - unused
severity:
  default-severity: info