name: Main release workflow
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - ".github/**"
      - "LICENSE"
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make